/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


float
calculate_prog_1(char *host, float n1, float n2, char op, CLIENT *clnt)
{	
	float  *result_1;
	variables  add_1_arg;
	float  *result_2;
	variables  sub_1_arg;
	float  *result_3;
	variables  mul_1_arg;
	float  *result_4;
	variables  div_1_arg;

	if(op == '+'){
		add_1_arg.a = n1;
		add_1_arg.b = n2;
		add_1_arg.op = op;
		result_1 = add_1(&add_1_arg, clnt);
		if(result_1 == (float*) NULL) {
			clnt_perror (clnt, "Error en la suma");
		}
		return *result_1;
	} 

	else if(op == '-'){
		sub_1_arg.a = n1;
		sub_1_arg.b = n2;
		sub_1_arg.op = op;
		result_2 = sub_1(&sub_1_arg, clnt);
		if(result_2 == (float*) NULL) {
			clnt_perror (clnt, "Error en la resta");
		}
		return *result_2;
	}

	else if(op == '*'){
		mul_1_arg.a = n1;
		mul_1_arg.b = n2;
		mul_1_arg.op = op;
		result_3 = mul_1(&mul_1_arg, clnt);
		if(result_3 == (float*) NULL) {
			clnt_perror (clnt, "Error en la multiplicacion");
		}
		return *result_3;
	}

	else if(op == '/'){
		div_1_arg.a = n1;
		div_1_arg.b = n2;
		div_1_arg.op = op;
		result_4 = div_1(&div_1_arg, clnt);
		if(result_4 == (float*) NULL) {
			clnt_perror (clnt, "Error en la division");
		}
		return *result_4;
	}
}


int
main (int argc, char *argv[])
{
	char *host;
	float a, b;
	char op;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("CALCULADORA RPC\n");	
	printf("Ingrese el primer numero\n");
	scanf("%f", &a);
	fflush(stdin);
	printf("Ingrese el segundo numero\n");
	scanf("%f", &b);
	fflush(stdin);
	printf("Elige la operacion a usar:\n'+' Suma\n'-' Resta\n'*' Multiplicacion\n'/' Division\n");
	scanf("%s", &op);
	host = argv[1];
	clnt = clnt_create(host, CALCULATE_PROG, CALCULATE_VER, "udp");
	if(clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	printf("La respuesta es: %.2f\n", calculate_prog_1(host, a, b, op, clnt));
	clnt_destroy(clnt);
	exit (0);
}
