/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct variables {
	float a;
	float b;
	char op;
};
typedef struct variables variables;

#define CALCULATE_PROG 0x2fffffff
#define CALCULATE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  float * add_1(variables *, CLIENT *);
extern  float * add_1_svc(variables *, struct svc_req *);
#define SUB 2
extern  float * sub_1(variables *, CLIENT *);
extern  float * sub_1_svc(variables *, struct svc_req *);
#define MUL 3
extern  float * mul_1(variables *, CLIENT *);
extern  float * mul_1_svc(variables *, struct svc_req *);
#define DIV 4
extern  float * div_1(variables *, CLIENT *);
extern  float * div_1_svc(variables *, struct svc_req *);
extern int calculate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  float * add_1();
extern  float * add_1_svc();
#define SUB 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define MUL 3
extern  float * mul_1();
extern  float * mul_1_svc();
#define DIV 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calculate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_variables (XDR *, variables*);

#else /* K&R C */
extern bool_t xdr_variables ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
