/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float * add_1_svc(variables *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->a + argp->b;
	printf("Sumando %.2f + %.2f\n", argp->a, argp->b);
	printf("La respuesta enviada es: %.2f\n", result);

	return &result;
}

float * sub_1_svc(variables *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->a - argp->b;
	printf("Restando %.2f + %.2f\n", argp->a, argp->b);
	printf("La respuesta enviada es: %.2f\n", result);

	return &result;
}

float * mul_1_svc(variables *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->a * argp->b;
	printf("Multiplicando %.2f + %.2f\n", argp->a, argp->b);
	printf("La respuesta enviada es: %.2f\n", result);

	return &result;
}

float * div_1_svc(variables *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->a / argp->b;
	printf("Dividiendo %.2f + %.2f\n", argp->a, argp->b);
	printf("La respuesta enviada es: %.2f\n", result);

	return &result;
}
